package report

import (
	"bytes"
	"fmt"
	"html/template"
	"os"
	"path/filepath"
	"strings"

	"github.com/repomind/repomind/internal/i18n"
	"github.com/repomind/repomind/internal/ir"
)

func WriteHTML(path string, analysis *ir.Analysis) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("create report directory: %w", err)
	}

	html, err := RenderHTML(analysis)
	if err != nil {
		return err
	}

	if err := os.WriteFile(path, []byte(html), 0o644); err != nil {
		return fmt.Errorf("write report: %w", err)
	}
	return nil
}

func RenderHTML(analysis *ir.Analysis) (string, error) {
	if analysis == nil {
		return "", fmt.Errorf("analysis is nil")
	}

	labels := labelsForLanguage(analysis.Language)
	tmpl, err := template.New("report").Funcs(template.FuncMap{
		"join": strings.Join,
		"dash": dash,
		"label": func(key string) string {
			if value, ok := labels[key]; ok {
				return value
			}
			return key
		},
		"htmlLang": func() string {
			if i18n.IsChinese(analysis.Language) {
				return "zh-CN"
			}
			return "en"
		},
	}).Parse(reportTemplate)
	if err != nil {
		return "", fmt.Errorf("parse report template: %w", err)
	}

	var buffer bytes.Buffer
	if err := tmpl.Execute(&buffer, analysis); err != nil {
		return "", fmt.Errorf("render report template: %w", err)
	}

	return buffer.String(), nil
}

func dash(value string) string {
	if strings.TrimSpace(value) == "" {
		return "-"
	}
	return value
}

func labelsForLanguage(language string) map[string]string {
	if i18n.IsChinese(language) {
		return map[string]string{
			"reportTitle":      "RepoMind 报告",
			"generatedBy":      "生成工具",
			"generatedAt":      "生成时间",
			"overview":         "概览",
			"files":            "文件数",
			"directories":      "目录数",
			"models":           "模型数",
			"routes":           "路由数",
			"projectSummary":   "项目总结",
			"modules":          "模块",
			"keyFlows":         "关键流程",
			"startHints":       "启动提示",
			"stack":            "技术栈",
			"backend":          "后端",
			"frontend":         "前端",
			"database":         "数据库",
			"cache":            "缓存",
			"queue":            "队列",
			"languagesConfig":  "语言与配置",
			"configFiles":      "配置文件",
			"packages":         "包/模块",
			"name":             "名称",
			"path":             "路径",
			"parent":           "父级",
			"type":             "类型",
			"dependencies":     "依赖",
			"directoryTree":    "目录结构",
			"databaseModels":   "数据库模型",
			"source":           "来源",
			"location":         "位置",
			"confidence":       "可信度",
			"evidence":         "证据",
			"fields":           "字段",
			"relations":        "关系",
			"apiRoutes":        "API 路由",
			"method":           "方法",
			"handler":          "处理函数",
			"erDiagram":        "ER 图",
			"apiMap":           "API 图",
			"callGraph":        "调用图",
			"packageGraph":     "Package 图",
			"emptyModules":     "未推断出模块。",
			"emptyFlows":       "未推断出流程。",
			"emptyStartHints":  "未推断出启动提示。",
			"emptySummary":     "未生成总结。",
			"emptyLanguages":   "未检测到语言。",
			"emptyConfig":      "未检测到配置文件。",
			"emptyPackages":    "未检测到 package 根目录。",
			"emptyDirectories": "未检测到目录。",
			"emptyModels":      "未检测到数据库模型。",
			"emptyRoutes":      "未检测到 API 路由。",
			"emptyER":          "未生成 ER 图。",
			"emptyAPI":         "未生成 API 图。",
			"emptyCallGraph":   "未生成调用图。",
			"limitedAnalysis":  "分析结果已被截断，部分大文件或调用边可能未包含在报告中。",
		}
	}
	return map[string]string{
		"reportTitle":      "RepoMind Report",
		"generatedBy":      "Generated by",
		"generatedAt":      "at",
		"overview":         "Overview",
		"files":            "Files",
		"directories":      "Directories",
		"models":           "Models",
		"routes":           "Routes",
		"projectSummary":   "Project Summary",
		"modules":          "Modules",
		"keyFlows":         "Key Flows",
		"startHints":       "Start Hints",
		"stack":            "Stack",
		"backend":          "Backend",
		"frontend":         "Frontend",
		"database":         "Database",
		"cache":            "Cache",
		"queue":            "Queue",
		"languagesConfig":  "Languages & Config",
		"configFiles":      "Config Files",
		"packages":         "Packages",
		"name":             "Name",
		"path":             "Path",
		"parent":           "Parent",
		"type":             "Type",
		"dependencies":     "Dependencies",
		"directoryTree":    "Directory Structure",
		"databaseModels":   "Database Models",
		"source":           "Source",
		"location":         "Location",
		"confidence":       "Confidence",
		"evidence":         "Evidence",
		"fields":           "Fields",
		"relations":        "Relations",
		"apiRoutes":        "API Routes",
		"method":           "Method",
		"handler":          "Handler",
		"erDiagram":        "ER Diagram",
		"apiMap":           "API Map",
		"callGraph":        "Call Graph",
		"packageGraph":     "Package Graph",
		"emptyModules":     "No modules inferred.",
		"emptyFlows":       "No flows inferred.",
		"emptyStartHints":  "No start hints inferred.",
		"emptySummary":     "No summary generated.",
		"emptyLanguages":   "No languages detected.",
		"emptyConfig":      "No config files detected.",
		"emptyPackages":    "No package roots detected.",
		"emptyDirectories": "No directories detected.",
		"emptyModels":      "No database models detected.",
		"emptyRoutes":      "No API routes detected.",
		"emptyER":          "No ER diagram generated.",
		"emptyAPI":         "No API map generated.",
		"emptyCallGraph":   "No call graph generated.",
		"limitedAnalysis":  "Analysis was truncated. Some large files or call edges may be omitted from this report.",
	}
}

const reportTemplate = `<!doctype html>
<html lang="{{htmlLang}}">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{{label "reportTitle"}} - {{.Repository.Name}}</title>
  <style>
    :root {
      color-scheme: light;
      --bg: #f7f7f4;
      --panel: #ffffff;
      --text: #1d2428;
      --muted: #65727a;
      --line: #dce2e5;
      --accent: #0f766e;
      --accent-soft: #d9f3ee;
      --code: #263238;
    }
    * { box-sizing: border-box; }
    body {
      margin: 0;
      background: var(--bg);
      color: var(--text);
      font: 14px/1.5 Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
    }
    header {
      border-bottom: 1px solid var(--line);
      background: var(--panel);
    }
    .wrap {
      width: min(1180px, calc(100vw - 32px));
      margin: 0 auto;
    }
    .topbar {
      min-height: 96px;
      display: flex;
      align-items: center;
      justify-content: space-between;
      gap: 24px;
    }
    h1 {
      margin: 0;
      font-size: 28px;
      line-height: 1.15;
      letter-spacing: 0;
    }
    h2 {
      margin: 0 0 14px;
      font-size: 18px;
      letter-spacing: 0;
    }
    h3 {
      margin: 18px 0 8px;
      font-size: 14px;
      letter-spacing: 0;
    }
    .muted { color: var(--muted); }
    main {
      padding: 24px 0 40px;
    }
    .grid {
      display: grid;
      grid-template-columns: repeat(12, 1fr);
      gap: 16px;
    }
    section {
      grid-column: span 12;
      background: var(--panel);
      border: 1px solid var(--line);
      border-radius: 8px;
      padding: 18px;
      min-width: 0;
    }
    .half { grid-column: span 6; }
    .third { grid-column: span 4; }
    .metric-row {
      display: grid;
      grid-template-columns: repeat(4, minmax(0, 1fr));
      gap: 10px;
    }
    .metric {
      border: 1px solid var(--line);
      border-radius: 8px;
      padding: 12px;
      background: #fbfcfc;
      min-height: 72px;
    }
    .metric strong {
      display: block;
      font-size: 22px;
      line-height: 1.1;
    }
    .pill-row {
      display: flex;
      flex-wrap: wrap;
      gap: 8px;
    }
    .pill {
      display: inline-flex;
      align-items: center;
      min-height: 28px;
      padding: 4px 9px;
      border-radius: 999px;
      background: var(--accent-soft);
      color: #075e57;
      font-size: 13px;
      white-space: nowrap;
    }
    table {
      width: 100%;
      border-collapse: collapse;
      table-layout: fixed;
    }
    th, td {
      padding: 9px 8px;
      border-bottom: 1px solid var(--line);
      text-align: left;
      vertical-align: top;
      overflow-wrap: anywhere;
    }
    th {
      font-size: 12px;
      color: var(--muted);
      font-weight: 650;
      text-transform: uppercase;
    }
    code, pre {
      font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, "Liberation Mono", monospace;
    }
    code {
      color: var(--code);
      background: #eef1f2;
      border-radius: 4px;
      padding: 2px 5px;
    }
    .tree {
      max-height: 420px;
      overflow: auto;
      border: 1px solid var(--line);
      border-radius: 8px;
      padding: 12px;
      background: #fbfcfc;
      color: var(--code);
      white-space: pre-wrap;
    }
    .mermaid {
      min-height: 180px;
      overflow: auto;
      border: 1px solid var(--line);
      border-radius: 8px;
      padding: 14px;
      background: #fbfcfc;
    }
    .empty {
      color: var(--muted);
      border: 1px dashed var(--line);
      border-radius: 8px;
      padding: 16px;
      background: #fbfcfc;
    }
    @media (max-width: 860px) {
      .topbar { align-items: flex-start; flex-direction: column; padding: 18px 0; }
      .half, .third { grid-column: span 12; }
      .metric-row { grid-template-columns: repeat(2, minmax(0, 1fr)); }
    }
    @media (max-width: 520px) {
      .metric-row { grid-template-columns: 1fr; }
      th, td { font-size: 13px; }
    }
  </style>
</head>
<body>
  <header>
    <div class="wrap topbar">
      <div>
        <h1>{{.Repository.Name}}</h1>
        <div class="muted">{{.Repository.Root}}</div>
      </div>
      <div class="muted">{{label "generatedBy"}} {{.GeneratedBy}} {{label "generatedAt"}} {{.Repository.AnalyzedAt}}</div>
    </div>
  </header>

  <main class="wrap">
    <div class="grid">
      <section>
        <h2>{{label "overview"}}</h2>
        {{if .Scan.Truncated}}<div class="empty">{{label "limitedAnalysis"}}</div>{{end}}
        {{if .Summary.Overview}}
        <p>{{.Summary.Overview}}</p>
        {{end}}
        <div class="metric-row">
          <div class="metric"><strong>{{.Scan.TotalFiles}}</strong><span class="muted">{{label "files"}}</span></div>
          <div class="metric"><strong>{{.Scan.TotalDirectories}}</strong><span class="muted">{{label "directories"}}</span></div>
          <div class="metric"><strong>{{len .Models}}</strong><span class="muted">{{label "models"}}</span></div>
          <div class="metric"><strong>{{len .Routes}}</strong><span class="muted">{{label "routes"}}</span></div>
        </div>
      </section>

      <section>
        <h2>{{label "projectSummary"}}</h2>
        {{if .Summary.Overview}}
        <p>{{.Summary.Overview}}</p>
        <div class="grid">
          <div class="third">
            <h3>{{label "modules"}}</h3>
            {{if .Summary.Modules}}<div class="pill-row">{{range .Summary.Modules}}<span class="pill">{{.}}</span>{{end}}</div>{{else}}<div class="empty">{{label "emptyModules"}}</div>{{end}}
          </div>
          <div class="third">
            <h3>{{label "keyFlows"}}</h3>
            {{if .Summary.KeyFlows}}<div class="pill-row">{{range .Summary.KeyFlows}}<span class="pill">{{.}}</span>{{end}}</div>{{else}}<div class="empty">{{label "emptyFlows"}}</div>{{end}}
          </div>
          <div class="third">
            <h3>{{label "startHints"}}</h3>
            {{if .Summary.StartHints}}<div class="pill-row">{{range .Summary.StartHints}}<span class="pill">{{.}}</span>{{end}}</div>{{else}}<div class="empty">{{label "emptyStartHints"}}</div>{{end}}
          </div>
        </div>
        {{else}}
        <div class="empty">{{label "emptySummary"}}</div>
        {{end}}
      </section>

      <section class="half">
        <h2>{{label "stack"}}</h2>
        <table>
          <tbody>
            <tr><th>{{label "backend"}}</th><td>{{dash .Stack.Backend}}</td></tr>
            <tr><th>{{label "frontend"}}</th><td>{{dash .Stack.Frontend}}</td></tr>
            <tr><th>{{label "database"}}</th><td>{{dash .Stack.Database}}</td></tr>
            <tr><th>{{label "cache"}}</th><td>{{dash .Stack.Cache}}</td></tr>
            <tr><th>{{label "queue"}}</th><td>{{dash .Stack.Queue}}</td></tr>
          </tbody>
        </table>
      </section>

      <section class="half">
        <h2>{{label "languagesConfig"}}</h2>
        {{if .Stack.Languages}}
        <div class="pill-row">{{range .Stack.Languages}}<span class="pill">{{.}}</span>{{end}}</div>
        {{else}}
        <div class="empty">{{label "emptyLanguages"}}</div>
        {{end}}
        <h3>{{label "configFiles"}}</h3>
        {{if .Stack.ConfigFiles}}
        <div class="pill-row">{{range .Stack.ConfigFiles}}<span class="pill">{{.}}</span>{{end}}</div>
        {{else}}
        <div class="empty">{{label "emptyConfig"}}</div>
        {{end}}
      </section>

      <section>
        <h2>{{label "packages"}}</h2>
        {{if .Packages}}
        <table>
          <thead><tr><th>{{label "name"}}</th><th>{{label "path"}}</th><th>{{label "parent"}}</th><th>{{label "dependencies"}}</th><th>{{label "type"}}</th><th>{{label "backend"}}</th><th>{{label "frontend"}}</th><th>{{label "database"}}</th><th>{{label "files"}}</th><th>{{label "models"}}</th><th>{{label "routes"}}</th></tr></thead>
          <tbody>
            {{range .Packages}}
            <tr>
              <td>{{.Name}}</td>
              <td><code>{{.Path}}</code></td>
              <td>{{if .Parent}}<code>{{.Parent}}</code>{{else}}-{{end}}</td>
              <td>{{range .Dependencies}}<code>{{.}}</code> {{else}}-{{end}}</td>
              <td>{{dash .Type}}</td>
              <td>{{dash .Stack.Backend}}</td>
              <td>{{dash .Stack.Frontend}}</td>
              <td>{{dash .Stack.Database}}</td>
              <td>{{.Files}}</td>
              <td>{{.Models}}</td>
              <td>{{.Routes}}</td>
            </tr>
            {{end}}
          </tbody>
        </table>
        {{else}}
        <div class="empty">{{label "emptyPackages"}}</div>
        {{end}}
      </section>

      <section>
        <h2>{{label "packageGraph"}}</h2>
        {{if .Diagrams.Package}}<pre class="mermaid">{{.Diagrams.Package}}</pre>{{else}}<div class="empty">{{label "emptyPackages"}}</div>{{end}}
      </section>

      <section class="half">
        <h2>{{label "directoryTree"}}</h2>
        {{if .Scan.Directories}}
        <div class="tree">{{range .Scan.Directories}}{{.}}
{{end}}</div>
        {{else}}
        <div class="empty">{{label "emptyDirectories"}}</div>
        {{end}}
      </section>

      <section class="half">
        <h2>{{label "files"}}</h2>
        <div class="tree">{{range .Scan.Files}}{{.Path}}
{{end}}</div>
      </section>

      <section>
        <h2>{{label "databaseModels"}}</h2>
        {{if .Models}}
        <table>
          <thead><tr><th>{{label "name"}}</th><th>{{label "source"}}</th><th>{{label "location"}}</th><th>{{label "confidence"}}</th><th>{{label "evidence"}}</th><th>{{label "fields"}}</th><th>{{label "relations"}}</th></tr></thead>
          <tbody>
            {{range .Models}}
            <tr>
              <td>{{.Name}}</td>
              <td>{{.Source}}</td>
              <td><code>{{.File}}{{if .Line}}:{{.Line}}{{end}}</code></td>
              <td>{{dash .Confidence}}</td>
              <td>{{if .Evidence}}<code>{{.Evidence}}</code>{{else}}-{{end}}</td>
              <td>{{range .Fields}}<code>{{.Name}}:{{.Type}}</code> {{end}}</td>
              <td>{{range .Relations}}<code>{{.Name}} -> {{.Target}}</code> {{end}}</td>
            </tr>
            {{end}}
          </tbody>
        </table>
        {{else}}
        <div class="empty">{{label "emptyModels"}}</div>
        {{end}}
      </section>

      <section>
        <h2>{{label "apiRoutes"}}</h2>
        {{if .Routes}}
        <table>
          <thead><tr><th>{{label "method"}}</th><th>{{label "path"}}</th><th>{{label "handler"}}</th><th>{{label "source"}}</th><th>{{label "location"}}</th><th>{{label "confidence"}}</th><th>{{label "evidence"}}</th></tr></thead>
          <tbody>
            {{range .Routes}}
            <tr>
              <td><code>{{.Method}}</code></td>
              <td>{{.Path}}</td>
              <td>{{.Handler}}</td>
              <td>{{.Source}}</td>
              <td><code>{{.File}}{{if .Line}}:{{.Line}}{{end}}</code></td>
              <td>{{dash .Confidence}}</td>
              <td>{{if .Evidence}}<code>{{.Evidence}}</code>{{else}}-{{end}}</td>
            </tr>
            {{end}}
          </tbody>
        </table>
        {{else}}
        <div class="empty">{{label "emptyRoutes"}}</div>
        {{end}}
      </section>

      <section class="half">
        <h2>{{label "erDiagram"}}</h2>
        {{if .Diagrams.ER}}<pre class="mermaid">{{.Diagrams.ER}}</pre>{{else}}<div class="empty">{{label "emptyER"}}</div>{{end}}
      </section>

      <section class="half">
        <h2>{{label "apiMap"}}</h2>
        {{if .Diagrams.API}}<pre class="mermaid">{{.Diagrams.API}}</pre>{{else}}<div class="empty">{{label "emptyAPI"}}</div>{{end}}
      </section>

      <section>
        <h2>{{label "callGraph"}}</h2>
        {{if .Diagrams.Call}}<pre class="mermaid">{{.Diagrams.Call}}</pre>{{else}}<div class="empty">{{label "emptyCallGraph"}}</div>{{end}}
      </section>
    </div>
  </main>

  <script type="module">
    import mermaid from "https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.esm.min.mjs";
    mermaid.initialize({ startOnLoad: true, theme: "default", securityLevel: "strict" });
  </script>
</body>
</html>
`
