package exporter

import (
	"fmt"
	"strings"

	"github.com/patrick892368/RepoMind/internal/ir"
)

func RenderToolContext(toolName string, analysis ir.Analysis) string {
	var builder strings.Builder
	builder.WriteString("# RepoMind Context for ")
	builder.WriteString(toolName)
	builder.WriteString("\n\n")
	builder.WriteString("This file is generated by RepoMind. Use it as a repository orientation layer before editing code.\n\n")
	builder.WriteString("- Read `.repomind/context.md` for the full repository summary.\n")
	builder.WriteString("- Read `.repomind/db-schema.md` before changing models or migrations.\n")
	builder.WriteString("- Read `.repomind/api-map.md` before changing API handlers or routes.\n")
	builder.WriteString("- Treat generated context as a guide; verify behavior in source before making changes.\n\n")
	builder.WriteString(RenderArchitecture(analysis))
	return builder.String()
}

func RenderContext(analysis ir.Analysis) string {
	var builder strings.Builder
	builder.WriteString("# RepoMind Repository Context\n\n")
	builder.WriteString(RenderArchitecture(analysis))
	builder.WriteString("\n")
	builder.WriteString(RenderDBSchema(analysis))
	builder.WriteString("\n")
	builder.WriteString(RenderAPIMap(analysis))
	return builder.String()
}

func RenderArchitecture(analysis ir.Analysis) string {
	var builder strings.Builder
	builder.WriteString("# Architecture\n\n")
	builder.WriteString("## Project\n\n")
	builder.WriteString("- Name: ")
	builder.WriteString(valueOrDash(analysis.Repository.Name))
	builder.WriteString("\n")
	builder.WriteString("- Root: `")
	builder.WriteString(analysis.Repository.Root)
	builder.WriteString("`\n")
	builder.WriteString("- Files: ")
	builder.WriteString(fmt.Sprintf("%d", analysis.Scan.TotalFiles))
	builder.WriteString("\n")
	builder.WriteString("- Directories: ")
	builder.WriteString(fmt.Sprintf("%d", analysis.Scan.TotalDirectories))
	builder.WriteString("\n\n")

	if analysis.Summary.Overview != "" {
		builder.WriteString("## Summary\n\n")
		builder.WriteString(analysis.Summary.Overview)
		builder.WriteString("\n\n")
	}

	builder.WriteString("## Stack\n\n")
	writeKV(&builder, "Backend", analysis.Stack.Backend)
	writeKV(&builder, "Frontend", analysis.Stack.Frontend)
	writeKV(&builder, "Database", analysis.Stack.Database)
	writeKV(&builder, "Cache", analysis.Stack.Cache)
	writeKV(&builder, "Queue", analysis.Stack.Queue)
	if len(analysis.Stack.PackageManager) > 0 {
		writeKV(&builder, "Package managers", strings.Join(analysis.Stack.PackageManager, ", "))
	}
	if len(analysis.Stack.ConfigFiles) > 0 {
		writeKV(&builder, "Config files", strings.Join(analysis.Stack.ConfigFiles, ", "))
	}

	if len(analysis.Packages) > 0 {
		builder.WriteString("\n## Packages\n\n")
		for _, pkg := range analysis.Packages {
			builder.WriteString("- `")
			builder.WriteString(pkg.Path)
			builder.WriteString("`")
			if pkg.Name != "" {
				builder.WriteString(" ")
				builder.WriteString(pkg.Name)
			}
			if pkg.Type != "" {
				builder.WriteString(" [")
				builder.WriteString(pkg.Type)
				builder.WriteString("]")
			}
			if pkg.Parent != "" {
				builder.WriteString(" parent=`")
				builder.WriteString(pkg.Parent)
				builder.WriteString("`")
			}
			if len(pkg.Dependencies) > 0 {
				builder.WriteString(" deps=")
				builder.WriteString(strings.Join(pkg.Dependencies, ", "))
			}
			builder.WriteString(fmt.Sprintf(" files=%d models=%d routes=%d", pkg.Files, pkg.Models, pkg.Routes))
			stackParts := nonEmptyValues(pkg.Stack.Backend, pkg.Stack.Frontend, pkg.Stack.Database)
			if len(stackParts) > 0 {
				builder.WriteString(" stack=")
				builder.WriteString(strings.Join(stackParts, ", "))
			}
			builder.WriteString("\n")
		}
		if analysis.Diagrams.Package != "" {
			builder.WriteString("\n```mermaid\n")
			builder.WriteString(analysis.Diagrams.Package)
			builder.WriteString("```\n")
		}
	}

	if len(analysis.Summary.Modules) > 0 {
		builder.WriteString("\n## Inferred Modules\n\n")
		for _, module := range analysis.Summary.Modules {
			builder.WriteString("- ")
			builder.WriteString(module)
			builder.WriteString("\n")
		}
	}

	if len(analysis.Summary.StartHints) > 0 {
		builder.WriteString("\n## Start Hints\n\n")
		for _, hint := range analysis.Summary.StartHints {
			builder.WriteString("- ")
			builder.WriteString(hint)
			builder.WriteString("\n")
		}
	}

	return builder.String()
}

func RenderDBSchema(analysis ir.Analysis) string {
	var builder strings.Builder
	builder.WriteString("# Database Schema\n\n")
	if len(analysis.Models) == 0 {
		builder.WriteString("No database models detected.\n")
		return builder.String()
	}

	for _, model := range analysis.Models {
		builder.WriteString("## ")
		builder.WriteString(model.Name)
		builder.WriteString("\n\n")
		builder.WriteString("- Source: ")
		builder.WriteString(model.Source)
		builder.WriteString("\n")
		builder.WriteString("- File: `")
		builder.WriteString(model.File)
		if model.Line > 0 {
			builder.WriteString(fmt.Sprintf(":%d", model.Line))
		}
		builder.WriteString("`\n")
		if model.Confidence != "" {
			builder.WriteString("- Confidence: ")
			builder.WriteString(model.Confidence)
			builder.WriteString("\n")
		}
		if model.Evidence != "" {
			builder.WriteString("- Evidence: `")
			builder.WriteString(model.Evidence)
			builder.WriteString("`\n")
		}
		if model.Table != "" {
			builder.WriteString("- Table: `")
			builder.WriteString(model.Table)
			builder.WriteString("`\n")
		}
		if len(model.Fields) > 0 {
			builder.WriteString("- Fields:\n")
			for _, field := range model.Fields {
				builder.WriteString("  - `")
				builder.WriteString(field.Name)
				builder.WriteString(": ")
				builder.WriteString(field.Type)
				builder.WriteString("`")
				if field.PrimaryKey {
					builder.WriteString(" primary key")
				}
				if field.Unique {
					builder.WriteString(" unique")
				}
				builder.WriteString("\n")
			}
		}
		if len(model.Relations) > 0 {
			builder.WriteString("- Relations:\n")
			for _, relation := range model.Relations {
				builder.WriteString("  - `")
				builder.WriteString(relation.Name)
				builder.WriteString(" -> ")
				builder.WriteString(relation.Target)
				builder.WriteString("` ")
				builder.WriteString(relation.Type)
				builder.WriteString("\n")
			}
		}
		builder.WriteString("\n")
	}

	if analysis.Diagrams.ER != "" {
		builder.WriteString("## Mermaid ER\n\n```mermaid\n")
		builder.WriteString(analysis.Diagrams.ER)
		builder.WriteString("```\n")
	}

	return builder.String()
}

func RenderAPIMap(analysis ir.Analysis) string {
	var builder strings.Builder
	builder.WriteString("# API Map\n\n")
	if len(analysis.Routes) == 0 {
		builder.WriteString("No API routes detected.\n")
		return builder.String()
	}

	for _, route := range analysis.Routes {
		builder.WriteString("- `")
		builder.WriteString(route.Method)
		builder.WriteString(" ")
		builder.WriteString(route.Path)
		builder.WriteString("`")
		if route.Handler != "" {
			builder.WriteString(" -> `")
			builder.WriteString(route.Handler)
			builder.WriteString("`")
		}
		builder.WriteString(" (")
		builder.WriteString(route.Source)
		builder.WriteString(", `")
		builder.WriteString(route.File)
		if route.Line > 0 {
			builder.WriteString(fmt.Sprintf(":%d", route.Line))
		}
		builder.WriteString("`)\n")
		if route.Confidence != "" || route.Evidence != "" {
			builder.WriteString("  Evidence: ")
			if route.Confidence != "" {
				builder.WriteString(route.Confidence)
				builder.WriteString(" confidence")
			}
			if route.Evidence != "" {
				if route.Confidence != "" {
					builder.WriteString(", ")
				}
				builder.WriteString("`")
				builder.WriteString(route.Evidence)
				builder.WriteString("`")
			}
			builder.WriteString("\n")
		}
	}

	if analysis.Diagrams.API != "" {
		builder.WriteString("\n## Mermaid API Map\n\n```mermaid\n")
		builder.WriteString(analysis.Diagrams.API)
		builder.WriteString("```\n")
	}

	return builder.String()
}

func writeKV(builder *strings.Builder, key string, value string) {
	builder.WriteString("- ")
	builder.WriteString(key)
	builder.WriteString(": ")
	builder.WriteString(valueOrDash(value))
	builder.WriteString("\n")
}

func valueOrDash(value string) string {
	if strings.TrimSpace(value) == "" {
		return "-"
	}
	return value
}

func nonEmptyValues(values ...string) []string {
	var result []string
	for _, value := range values {
		if strings.TrimSpace(value) != "" {
			result = append(result, value)
		}
	}
	return result
}
